const DEP__OBJ = [
  {
    "@id": "/core_api/company/departments/1",
    "@type": "Company Departments",
    "id": 1,
    "title": "DEMO 1",
    "isActive": true,
    "isMain": true,
    "chief": {
      "@id": "/core_api/company/users/6",
      "@type": "Company Users",
      "isActive": true,
      "name": "Богдан",
      "lastName": "Назарок",
      "patronymic": "Михайлович",
      "fullName": "Назарок Богдан Михайлович",
      "fullNameEnglish": "Богдан Михайлович Назарок",
      "email": "nazarok.b@itua.com.ua",
      "phones": ["380500755207"],
      "position": "Адмін",
      "id": 6
    },
    "users": [
      {
        "@id": "/core_api/company/users/8",
        "@type": "Company Users",
        "isActive": true,
        "name": "Front",
        "lastName": "Front",
        "fullName": "Front Front",
        "fullNameEnglish": "Front Front",
        "email": "front@test.ua",
        "id": 8
      }
    ],
    "lft": 1,
    "lvl": 0,
    "rgt": 12,
    "parent": "/core_api/company/departments/1",
    "isRemoved": false,
    "createdBy": {
      "@id": "/core_api/company/users/6",
      "@type": "Company Users",
      "isActive": true,
      "name": "Богдан",
      "lastName": "Назарок",
      "patronymic": "Михайлович",
      "fullName": "Назарок Богдан Михайлович",
      "fullNameEnglish": "Богдан Михайлович Назарок",
      "email": "nazarok.b@itua.com.ua",
      "phones": ["380500755207"],
      "position": "Адмін",
      "id": 6
    },
    "createdAt": "2024-05-06T17:31:52+03:00",
    "updatedBy": {
      "@id": "/core_api/company/users/6",
      "@type": "Company Users",
      "isActive": true,
      "name": "Богдан",
      "lastName": "Назарок",
      "patronymic": "Михайлович",
      "fullName": "Назарок Богдан Михайлович",
      "fullNameEnglish": "Богдан Михайлович Назарок",
      "email": "nazarok.b@itua.com.ua",
      "phones": ["380500755207"],
      "position": "Адмін",
      "id": 6
    },
    "updatedAt": "2024-10-10T13:49:17+03:00"
  },
  {
    "@id": "/core_api/company/departments/3",
    "@type": "Company Departments",
    "id": 3,
    "title": "DEMO 1.2",
    "isActive": true,
    "isMain": false,
    "chief": {
      "@id": "/core_api/company/users/7",
      "@type": "Company Users",
      "isActive": true,
      "name": "DEMO",
      "lastName": "DEMO",
      "fullName": "DEMO DEMO",
      "fullNameEnglish": "DEMO DEMO",
      "email": "danilmuhaew@gmail.com",
      "id": 7
    },
    "users": [],
    "lft": 12,
    "lvl": 1,
    "rgt": 13,
    "parent": {
      "@id": "/core_api/company/departments/1",
      "@type": "Company Departments",
      "id": 1,
      "title": "DEMO 1",
      "isActive": true,
      "isMain": true,
      "lft": 1,
      "lvl": 0,
      "rgt": 12,
      "isRemoved": false,
      "createdBy": {
        "@id": "/core_api/company/users/6",
        "@type": "Company Users",
        "isActive": true,
        "name": "Богдан",
        "lastName": "Назарок",
        "patronymic": "Михайлович",
        "fullName": "Назарок Богдан Михайлович",
        "fullNameEnglish": "Богдан Михайлович Назарок",
        "email": "nazarok.b@itua.com.ua",
        "phones": ["380500755207"],
        "position": "Адмін",
        "id": 6
      },
      "createdAt": "2024-05-06T17:31:52+03:00",
      "updatedBy": {
        "@id": "/core_api/company/users/6",
        "@type": "Company Users",
        "isActive": true,
        "name": "Богдан",
        "lastName": "Назарок",
        "patronymic": "Михайлович",
        "fullName": "Назарок Богдан Михайлович",
        "fullNameEnglish": "Богдан Михайлович Назарок",
        "email": "nazarok.b@itua.com.ua",
        "phones": ["380500755207"],
        "position": "Адмін",
        "id": 6
      },
      "updatedAt": "2024-10-10T13:49:17+03:00"
    },
    "isRemoved": false,
    "createdBy": {
      "@id": "/core_api/company/users/6",
      "@type": "Company Users",
      "isActive": true,
      "name": "Богдан",
      "lastName": "Назарок",
      "patronymic": "Михайлович",
      "fullName": "Назарок Богдан Михайлович",
      "fullNameEnglish": "Богдан Михайлович Назарок",
      "email": "nazarok.b@itua.com.ua",
      "phones": ["380500755207"],
      "position": "Адмін",
      "id": 6
    }
  }
];
